## < 분류 >
[DataManim](https://www.datamanim.com/dataset/03_dataq/index_big_python.html)의 2유형 연습문제 푸리푸리
- 서비스 이탈 예측
- 이직여부 판단
- 정시 배송 여부 판단
- 성인 건강검진

### 서비스 이탈 예측 데이터
- 고객의 신상정보 데이터를 통한 회사 서비스 이탈 예측

In [6]:
# import pagkage
import pandas as pd
import numpy as np
import sklearn

# read data
df_X = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/churnk/X_train.csv")
df_y = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/churnk/y_train.csv")
df_test = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/churnk/X_test.csv")

In [7]:
# data eda
print(df_X.info())
df_X.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6499 entries, 0 to 6498
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CustomerId       6499 non-null   int64  
 1   Surname          6499 non-null   object 
 2   CreditScore      6499 non-null   int64  
 3   Geography        6499 non-null   object 
 4   Gender           6499 non-null   object 
 5   Age              6499 non-null   int64  
 6   Tenure           6499 non-null   int64  
 7   Balance          6499 non-null   float64
 8   NumOfProducts    6499 non-null   int64  
 9   HasCrCard        6499 non-null   int64  
 10  IsActiveMember   6499 non-null   int64  
 11  EstimatedSalary  6499 non-null   float64
dtypes: float64(2), int64(7), object(3)
memory usage: 609.4+ KB
None


CustomerId    Surname  CreditScore Geography  Gender  Age  Tenure  \
0    15799217   Zetticci          791   Germany  Female   35       7   
1    15748986    Bischof          705   Germany    Male   42       8   
2    15722004     Hsiung          543    France  Female   31       4   
3    15780966  Pritchard          709    France  Female   32       2   
4    15636731      Ts'ai          714   Germany  Female   36       1   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0   52436.20              1          1               0        161051.75  
1  166685.92              2          1               1         55313.51  
2  138317.94              1          0               0         61843.73  
3       0.00              2          0               0        109681.29  
4  101609.01              2          1               1           447.73

In [8]:
print(df_y.info())
df_y.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6499 entries, 0 to 6498
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerId  6499 non-null   int64
 1   Exited      6499 non-null   int64
dtypes: int64(2)
memory usage: 101.7 KB
None


CustomerId  Exited
0    15799217       0
1    15748986       0
2    15722004       0
3    15780966       0
4    15636731       0

In [9]:
print(df_test.info())
df_test.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3501 entries, 0 to 3500
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CustomerId       3501 non-null   int64  
 1   Surname          3501 non-null   object 
 2   CreditScore      3501 non-null   int64  
 3   Geography        3501 non-null   object 
 4   Gender           3501 non-null   object 
 5   Age              3501 non-null   int64  
 6   Tenure           3501 non-null   int64  
 7   Balance          3501 non-null   float64
 8   NumOfProducts    3501 non-null   int64  
 9   HasCrCard        3501 non-null   int64  
 10  IsActiveMember   3501 non-null   int64  
 11  EstimatedSalary  3501 non-null   float64
dtypes: float64(2), int64(7), object(3)
memory usage: 328.3+ KB
None


CustomerId      Surname  CreditScore Geography  Gender  Age  Tenure  \
0    15601012     Abdullah          802    France  Female   60       3   
1    15734762     Ignatiev          602    France  Female   56       3   
2    15586757  Anenechukwu          801    France  Female   32       4   
3    15590888         Wade          693     Spain  Female   34      10   
4    15726087        Ch'in          592    France  Female   62       5   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0   92887.06              1          1               0         39473.63  
1  115895.22              3          1               0          4176.17  
2   75170.54              1          1               1         37898.50  
3  107556.06              2          0               0        154631.35  
4       0.00              1          1               1        100941.57

In [11]:
# 데이터 전처리, 결측치는 없어서 명목형 변수 라벨링만 하면 될 것 같음
# 합쳐서 라벨링 후 분리, 6499 / 3501
df_sum = pd.concat([df_X, df_test])
# df_sum.info()
# 모르겠으면 help(pd.concat)

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_sum['Surname'] = le.fit_transform(df_sum['Surname'])
df_sum['Geography'] = le.fit_transform(df_sum['Geography'])
df_sum['Gender'] = le.fit_transform(df_sum['Gender'])

In [13]:
# data split
df_X = df_sum[:6499]
print(df_X.shape)
df_test = df_sum[6499:]
print(df_test.shape)

(6499, 12)
(3501, 12)


In [20]:
# data split
from sklearn.model_selection import train_test_split
X = df_X
y = df_y['Exited']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5199, 12)
(1300, 12)
(5199,)
(1300,)


In [21]:
# modeling - randomforestclissifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state = 42, max_depth = 3)
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=3, random_state=42)

In [22]:
# predict
pred = rfc.predict(X_test)
print(pred)

[0 0 0 ... 0 0 0]


In [23]:
# 성능확인
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("accuracy : ", accuracy_score(y_test, pred))
print("confusion_matrix : ", confusion_matrix(y_test, pred))
print("report : ", classification_report(y_test, pred))


accuracy :  0.8115384615384615
confusion_matrix :  [[1022    0]
 [ 245   33]]
report :                precision    recall  f1-score   support

           0       0.81      1.00      0.89      1022
           1       1.00      0.12      0.21       278

    accuracy                           0.81      1300
   macro avg       0.90      0.56      0.55      1300
weighted avg       0.85      0.81      0.75      1300



In [25]:
# test data에 대해서 분류
pred_test = rfc.predict(df_test)
print(pred_test)

res = pd.DataFrame(pred_test, columns = ['Exited_Predict'])
res.to_csv("result.csv", index = False)

[0 1 0 ... 0 0 0]


In [28]:
test = pd.read_csv("result.csv")
test['Exited_Predict'].value_counts()

Exited_Predict
0    3416
1      85
Name: count, dtype: int64

In [29]:
# 검증용
df_ans = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/churnk/y_test.csv")
df_ans.head()

CustomerId  Exited
0    15601012       1
1    15734762       1
2    15586757       0
3    15590888       0
4    15726087       0

In [30]:
df_ans['Exited'].value_counts()

Exited
0    2788
1     713
Name: count, dtype: int64

In [32]:
# df_ans의 실제 'Exited' 값과 test의 예측된 'Exited_Predict' 값을 비교
actual_exited = df_ans['Exited']
predicted_exited = test['Exited_Predict']

print("Accuracy Score:", accuracy_score(actual_exited, predicted_exited))
print("Confusion Matrix:\n", confusion_matrix(actual_exited, predicted_exited))
print("Classification Report:\n", classification_report(actual_exited, predicted_exited))

Accuracy Score: 0.8177663524707226
Confusion Matrix:
 [[2783    5]
 [ 633   80]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      1.00      0.90      2788
           1       0.94      0.11      0.20       713

    accuracy                           0.82      3501
   macro avg       0.88      0.56      0.55      3501
weighted avg       0.84      0.82      0.76      3501



### 이직여부 판단 데이터 - 보류
- 이직여부 판단하기 target : 1-이직, 0-이직X

In [200]:
# import pakage
import pandas as pd
import numpy as np
import sklearn

# RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

# split
from sklearn.model_selection import train_test_split

In [201]:
# data
df_X = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/X_train.csv")
df_y = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/y_train.csv")
df_test = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/X_test.csv")

In [202]:
print(df_X.info())
df_X.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12452 entries, 0 to 12451
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   enrollee_id             12452 non-null  int64  
 1   city                    12452 non-null  object 
 2   city_development_index  12452 non-null  float64
 3   gender                  9535 non-null   object 
 4   relevent_experience     12452 non-null  object 
 5   enrolled_university     12195 non-null  object 
 6   education_level         12137 non-null  object 
 7   major_discipline        10586 non-null  object 
 8   experience              12415 non-null  object 
 9   company_size            8600 non-null   object 
 10  company_type            8471 non-null   object 
 11  last_new_job            12179 non-null  object 
 12  training_hours          12452 non-null  int64  
dtypes: float64(1), int64(2), object(10)
memory usage: 1.2+ MB
None


enrollee_id      city  city_development_index gender  \
0        25298  city_138                   0.836   Male   
1         4241  city_160                   0.920   Male   
2        24086   city_57                   0.866   Male   
3        26773   city_16                   0.910   Male   
4        32325  city_143                   0.740    NaN   

       relevent_experience enrolled_university education_level  \
0   No relevent experience    Full time course     High School   
1   No relevent experience    Full time course     High School   
2   No relevent experience       no_enrollment        Graduate   
3  Has relevent experience       no_enrollment        Graduate   
4   No relevent experience    Full time course        Graduate   

  major_discipline experience company_size company_type last_new_job  \
0              NaN          5      100-500      Pvt Ltd            1   
1              NaN          5          NaN          NaN            1   
2             STEM         10          NaN          NaN            1   
3             STEM        >20        50-99      Pvt Ltd           >4   
4             STEM          5          NaN          NaN        never   

   training_hours  
0              45  
1              17  
2              50  
3             135  
4              17

In [203]:
print(df_y.info())
df_y.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12452 entries, 0 to 12451
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   enrollee_id  12452 non-null  int64  
 1   target       12452 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 194.7 KB
None


enrollee_id  target
0        25298     0.0
1         4241     1.0
2        24086     0.0
3        26773     0.0
4        32325     1.0

In [204]:
print(df_test.info())
df_test.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6706 entries, 0 to 6705
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   enrollee_id             6706 non-null   int64  
 1   city                    6706 non-null   object 
 2   city_development_index  6706 non-null   float64
 3   gender                  5115 non-null   object 
 4   relevent_experience     6706 non-null   object 
 5   enrolled_university     6577 non-null   object 
 6   education_level         6561 non-null   object 
 7   major_discipline        5759 non-null   object 
 8   experience              6678 non-null   object 
 9   company_size            4620 non-null   object 
 10  company_type            4547 non-null   object 
 11  last_new_job            6556 non-null   object 
 12  training_hours          6706 non-null   int64  
dtypes: float64(1), int64(2), object(10)
memory usage: 681.2+ KB
None


enrollee_id      city  city_development_index  gender  \
0         7129   city_23                   0.899    Male   
1        31037   city_44                   0.725    Male   
2        22179  city_103                   0.920    Male   
3        29724   city_50                   0.896    Male   
4        17977  city_149                   0.689  Female   

       relevent_experience enrolled_university education_level  \
0   No relevent experience       no_enrollment        Graduate   
1   No relevent experience    Part time course         Masters   
2   No relevent experience    Full time course        Graduate   
3   No relevent experience    Full time course        Graduate   
4  Has relevent experience    Full time course         Masters   

  major_discipline experience company_size company_type last_new_job  \
0             STEM          2          NaN          NaN            1   
1             STEM          5          NaN          NaN        never   
2             STEM          7          NaN          NaN            2   
3             STEM          7          NaN          NaN        never   
4             STEM         19        50-99      Pvt Ltd            1   

   training_hours  
0              23  
1              39  
2             262  
3              78  
4             125

In [205]:
# 결측치가 너무 많은데요? -> 일단 그냥 함
print(df_X.isnull().sum())

enrollee_id                  0
city                         0
city_development_index       0
gender                    2917
relevent_experience          0
enrolled_university        257
education_level            315
major_discipline          1866
experience                  37
company_size              3852
company_type              3981
last_new_job               273
training_hours               0
dtype: int64


In [206]:
# print(x_train.info())
# print(x_train.nunique())
# print(x_train.isnull().sum())
# 결측치가 있지만 따로 처리하지 않고 더미화

x_train = df_X
y_train = df_y
x_test = df_test
# 범주형 변수인데 적당히 많은 unique값을 가진 컬럼은 날린다.
drop_col = ['enrollee_id','city','company_type','experience']
x_train_drop = x_train.drop(columns = drop_col)
x_test_drop = x_test.drop(columns = drop_col)

# import sklearn
# print(sklearn.__all__)
# import sklearn.model_selection
# print(dir(sklearn.model_selection))

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
x_train_dummies = pd.get_dummies(x_train_drop)
y = y_train['target'].astype('int')


x_test_dummies = pd.get_dummies(x_test_drop)
# train과 컬럼 순서 동일하게 하기 (더미화 하면서 순서대로 정렬을 이미 하기 때문에 오류가 난다면 해당 컬럼이 누락된것)
x_test_dummies = x_test_dummies[x_train_dummies.columns]
# print(help(train_test_split))



X_train, X_validation, Y_train, Y_validation = train_test_split(x_train_dummies, y, test_size=0.33, random_state=42)
rf = RandomForestClassifier(random_state =23)
rf.fit(X_train,Y_train)

# import sklearn.metrics
# print(dir(sklearn.metrics))

from sklearn.metrics import accuracy_score , f1_score, recall_score, roc_auc_score ,precision_score

#model_score
predict_train_label = rf.predict(X_train)
predict_train_proba = rf.predict_proba(X_train)[:,1]

predict_validation_label = rf.predict(X_validation)
predict_validation_prob = rf.predict_proba(X_validation)[:,1]


# 문제에서 묻는 것에 따라 모델 성능 확인하기
# 정확도 (accuracy) , f1_score , recall , precision -> model.predict로 결과뽑기
# auc , 확률이라는 표현있으면 model.predict_proba로 결과뽑고 첫번째 행의 값을 가져오기 model.predict_proba()[:,1]
print('train accuracy :', accuracy_score(Y_train,predict_train_label))
print('validation accuracy :', accuracy_score(Y_validation,predict_validation_label))
print('\n')
print('train f1_score :', f1_score(Y_train,predict_train_label))
print('validation f1_score :', f1_score(Y_validation,predict_validation_label))
print('\n')
print('train recall_score :', recall_score(Y_train,predict_train_label))
print('validation recall_score :', recall_score(Y_validation,predict_validation_label))
print('\n')
print('train precision_score :', precision_score(Y_train,predict_train_label))
print('validation precision_score :', precision_score(Y_validation,predict_validation_label))
print('\n')
print('train auc :', roc_auc_score(Y_train,predict_train_proba))
print('validation auc :', roc_auc_score(Y_validation,predict_validation_prob))


# test데이터 마찬가지 위와 같은 방식
predict_test_label = rf.predict(x_test_dummies)
predict_test_proba = rf.predict_proba(x_test_dummies)[:,1]


# accuracy, f1_score, recall, precision
#pd.DataFrame({'enrollee_id': x_test.enrollee_id, 'target': predict_test_label}).to_csv('003000000.csv', index=False)

# auc, 확률
#pd.DataFrame({'enrollee_id': x_test.enrollee_id, 'target': predict_test_proba}).to_csv('003000000.csv', index=False)

train accuracy : 0.9965236154399425
validation accuracy : 0.7535279805352798


train f1_score : 0.9929731039496001
validation f1_score : 0.42736009044657997


train recall_score : 0.9927325581395349
validation recall_score : 0.3631123919308357


train precision_score : 0.9932137663596704
validation precision_score : 0.5192307692307693


train auc : 0.9998907607098495
validation auc : 0.740677513569584


In [208]:
# =========================================
# 1. 데이터 로드
# =========================================
import pandas as pd

df_X = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/X_train.csv")
df_y = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/y_train.csv")
df_test = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/X_test.csv")

X_train_raw = df_X.copy()
y_train_raw = df_y.copy()
X_test_raw = df_test.copy()

# =========================================
# 2. 전처리 (drop + 더미)
# =========================================

# unique가 지나치게 많거나 필요 없는 컬럼 제거
drop_cols = ['enrollee_id', 'city', 'company_type', 'experience']

X_train = X_train_raw.drop(columns=drop_cols)
X_test = X_test_raw.drop(columns=drop_cols)

# y 값 변환
y = y_train_raw['target'].astype(int)

# get_dummies
X_train_dummies = pd.get_dummies(X_train)
X_test_dummies = pd.get_dummies(X_test)

# train/test 컬럼 맞추기
X_test_dummies = X_test_dummies.reindex(columns=X_train_dummies.columns, fill_value=0)

# =========================================
# 3. Train/Validation Split
# =========================================
from sklearn.model_selection import train_test_split

X_tr, X_val, y_tr, y_val = train_test_split(
    X_train_dummies, y, test_size=0.2, random_state=42
)

# =========================================
# 4. 모델 학습
# =========================================
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=23)
model.fit(X_tr, y_tr)

# =========================================
# 5. 예측
# =========================================
pred_tr = model.predict(X_tr)
pred_val = model.predict(X_val)

proba_tr = model.predict_proba(X_tr)[:, 1]
proba_val = model.predict_proba(X_val)[:, 1]

# =========================================
# 6. 성능 평가
# =========================================
from sklearn.metrics import (
    accuracy_score, f1_score, recall_score, precision_score,
    roc_auc_score, confusion_matrix, classification_report
)

print("====== Train Performance ======")
print("Accuracy :", accuracy_score(y_tr, pred_tr))
print("F1 Score :", f1_score(y_tr, pred_tr))
print("Recall   :", recall_score(y_tr, pred_tr))
print("Precision:", precision_score(y_tr, pred_tr))
print("AUC      :", roc_auc_score(y_tr, proba_tr))
print("Confusion Matrix:\n", confusion_matrix(y_tr, pred_tr))

print("\n====== Validation Performance ======")
print("Accuracy :", accuracy_score(y_val, pred_val))
print("F1 Score :", f1_score(y_val, pred_val))
print("Recall   :", recall_score(y_val, pred_val))
print("Precision:", precision_score(y_val, pred_val))
print("AUC      :", roc_auc_score(y_val, proba_val))
print("Confusion Matrix:\n", confusion_matrix(y_val, pred_val))

# =========================================
# 7. Test 데이터 예측 (제출파일 형태)
# =========================================
pred_test_label = model.predict(X_test_dummies)
pred_test_proba = model.predict_proba(X_test_dummies)[:, 1]

# 예시: 레이블 제출
# pd.DataFrame({'enrollee_id': X_test_raw.enrollee_id,
#               'target': pred_test_label}).to_csv('submit_label.csv', index=False)

# 예시: 확률 제출 (AUC 기반 문제)
# pd.DataFrame({'enrollee_id': X_test_raw.enrollee_id,
#               'target': pred_test_proba}).to_csv('submit_proba.csv', index=False)


====== Train Performance ======
Accuracy : 0.9958839473948399
F1 Score : 0.9917455204348702
Recall   : 0.9907481898632341
Precision: 0.992744860943168
AUC      : 0.999841601261378
Confusion Matrix:
 [[7457   18]
 [  23 2463]]

====== Validation Performance ======
Accuracy : 0.7543155359293456
F1 Score : 0.4312267657992565
Recall   : 0.37479806138933763
Precision: 0.5076586433260394
AUC      : 0.738844617731936
Confusion Matrix:
 [[1647  225]
 [ 387  232]]


### 정시 배송 여부 판단 - 2회 기출
- 1: 정시배송 , 0: 정시미배송

In [92]:
import pandas as pd
import numpy as np
import sklearn

# randomforest
from sklearn.ensemble import RandomForestClassifier

# model split
from sklearn.model_selection import train_test_split

In [93]:
df_X = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/shipping/X_train.csv")
df_y = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/shipping/y_train.csv")
df_test = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/shipping/X_test.csv")

In [83]:
# df_X.info()

In [84]:
# df_X.head()

In [85]:
# df_test.info()

In [86]:
# df_test.head()

In [87]:
# df_y.head()

In [105]:
# 데이터는 결측치 없고, 명목형 변수 인코딩 해줘야 함.
df_sum = pd.concat([df_X, df_test])
df_sum.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10999 entries, 0 to 4400
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ID                   10999 non-null  int64 
 1   Warehouse_block      10999 non-null  object
 2   Mode_of_Shipment     10999 non-null  object
 3   Customer_care_calls  10999 non-null  object
 4   Customer_rating      10999 non-null  int64 
 5   Cost_of_the_Product  10999 non-null  int64 
 6   Prior_purchases      10999 non-null  int64 
 7   Product_importance   10999 non-null  object
 8   Gender               10999 non-null  object
 9   Discount_offered     10999 non-null  int64 
 10  Weight_in_gms        10999 non-null  int64 
dtypes: int64(6), object(5)
memory usage: 1.0+ MB


In [106]:
# 전부 라벨인코딩 실시할 것임
print(df_sum['Warehouse_block'].value_counts()) # labelencoding
print(df_sum['Mode_of_Shipment'].value_counts()) # getdummies
print(df_sum['Customer_care_calls'].value_counts()) # labelencoding
print(df_sum['Product_importance'].value_counts()) # labelencoding
print(df_sum['Gender'].value_counts()) # 원핫


Warehouse_block
F    3666
D    1834
A    1833
C    1833
B    1833
Name: count, dtype: int64
Mode_of_Shipment
Ship      7462
Flight    1777
Road      1760
Name: count, dtype: int64
Customer_care_calls
4     3557
3     3217
5     2328
6     1013
2      638
$7     246
Name: count, dtype: int64
Product_importance
low       5297
medium    4754
high       948
Name: count, dtype: int64
Gender
F    5545
M    5454
Name: count, dtype: int64


In [107]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df_sum['Warehouse_block'] = le.fit_transform(df_sum['Warehouse_block'])
# df_sum['Mode_of_Shipment'] = le.fit_transform(df_sum['Mode_of_Shipment'])
# pd.get_dummies(df, col)
df_sum = pd.get_dummies(df_sum, columns=['Mode_of_Shipment'])
df_sum['Customer_care_calls'] = le.fit_transform(df_sum['Customer_care_calls'])
df_sum['Product_importance'] = le.fit_transform(df_sum['Product_importance'])
df_sum['Gender'] = le.fit_transform(df_sum['Gender'])

df_sum.head()
df_sum.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10999 entries, 0 to 4400
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       10999 non-null  int64
 1   Warehouse_block          10999 non-null  int64
 2   Customer_care_calls      10999 non-null  int64
 3   Customer_rating          10999 non-null  int64
 4   Cost_of_the_Product      10999 non-null  int64
 5   Prior_purchases          10999 non-null  int64
 6   Product_importance       10999 non-null  int64
 7   Gender                   10999 non-null  int64
 8   Discount_offered         10999 non-null  int64
 9   Weight_in_gms            10999 non-null  int64
 10  Mode_of_Shipment_Flight  10999 non-null  bool 
 11  Mode_of_Shipment_Road    10999 non-null  bool 
 12  Mode_of_Shipment_Ship    10999 non-null  bool 
dtypes: bool(3), int64(10)
memory usage: 977.5 KB


In [109]:
df_sum['Mode_of_Shipment_Flight'].astype(int)
df_sum['Mode_of_Shipment_Road'].astype(int)
df_sum['Mode_of_Shipment_Ship'].astype(int)

0       0
1       1
2       0
3       1
4       0
       ..
4396    0
4397    0
4398    0
4399    1
4400    1
Name: Mode_of_Shipment_Ship, Length: 10999, dtype: int64

In [110]:
# 6598 / 4401 개로 다시 분리
df_X = df_sum[:6598]
df_test = df_sum[6598:]
print(df_X.shape)
print(df_test.shape)

(6598, 13)
(4401, 13)


In [111]:
# train_test_split
X = df_X
y = df_y['Reached.on.Time_Y.N']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [112]:
# rfc 모델
rfc = RandomForestClassifier(random_state = 42, max_depth=5)
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, random_state=42)

In [113]:
pred = rfc.predict(X_test)
print(pred)

[0 0 0 ... 1 1 0]


In [114]:
# 성능 평가
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))
print(accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       0.56      0.97      0.71       806
           1       0.95      0.48      0.64      1174

    accuracy                           0.68      1980
   macro avg       0.76      0.72      0.68      1980
weighted avg       0.79      0.68      0.67      1980

[[778  28]
 [606 568]]
0.6797979797979798


In [115]:
# test set
pred_test = rfc.predict(df_test)
print(pred_test)

[0 0 0 ... 0 0 1]


In [116]:
result = pd.DataFrame(pred_test, columns = ['Reached.on.Time_Y.N'])
result.to_csv("result.csv", index = False)


In [117]:
res = pd.read_csv("result.csv")
print(res)

      Reached.on.Time_Y.N
0                       0
1                       0
2                       0
3                       0
4                       1
...                   ...
4396                    1
4397                    0
4398                    0
4399                    0
4400                    1

[4401 rows x 1 columns]


In [118]:
# 실제 데이터셋과 결과 비교
df_val = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/shipping/y_test.csv")
df_val.head()

ID  Reached.on.Time_Y.N
0  6811                    0
1  4320                    0
2  5732                    1
3  7429                    0
4  2191                    1

In [119]:
print(df_val['Reached.on.Time_Y.N'].value_counts())
print(res['Reached.on.Time_Y.N'].value_counts())

Reached.on.Time_Y.N
1    2626
0    1775
Name: count, dtype: int64
Reached.on.Time_Y.N
0    3066
1    1335
Name: count, dtype: int64


In [120]:
# 실제 데이터 셋과 정확도 비교
# df_ans의 실제 'Exited' 값과 test의 예측된 'Exited_Predict' 값을 비교
actual_exited = df_val['Reached.on.Time_Y.N']
predicted_exited = res['Reached.on.Time_Y.N']

print("Accuracy Score:", accuracy_score(actual_exited, predicted_exited))
print("Confusion Matrix:\n", confusion_matrix(actual_exited, predicted_exited))
print("Classification Report:\n", classification_report(actual_exited, predicted_exited))

Accuracy Score: 0.6784821631447399
Confusion Matrix:
 [[1713   62]
 [1353 1273]]
Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.97      0.71      1775
           1       0.95      0.48      0.64      2626

    accuracy                           0.68      4401
   macro avg       0.76      0.72      0.68      4401
weighted avg       0.79      0.68      0.67      4401



### 성인 건강검진 데이터
- 데이터 설명 : 2018년도 성인의 건강검 진데이터 (종속변수 : 흡연상태 1- 흡연, 0-비흡연 )


In [187]:
import pandas as pd
import numpy as np
import sklearn

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [188]:
df_X = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/smoke/x_train.csv")
df_y = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/smoke/y_train.csv")
df_test = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/smoke/x_test.csv")

In [124]:
df_X.head()
df_X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44553 entries, 0 to 44552
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   ID           44553 non-null  int64  
 1   성별코드         44553 non-null  object 
 2   연령대코드(5세단위)  44553 non-null  int64  
 3   신장(5Cm단위)    44553 non-null  int64  
 4   체중(5Kg단위)    44553 non-null  int64  
 5   허리둘레         44553 non-null  float64
 6   시력(좌)        44553 non-null  float64
 7   시력(우)        44553 non-null  float64
 8   청력(좌)        44553 non-null  float64
 9   청력(우)        44553 non-null  float64
 10  수축기혈압        44553 non-null  float64
 11  이완기혈압        44553 non-null  float64
 12  식전혈당(공복혈당)   44553 non-null  float64
 13  총콜레스테롤       44553 non-null  float64
 14  트리글리세라이드     44553 non-null  float64
 15  HDL콜레스테롤     44553 non-null  float64
 16  LDL콜레스테롤     44553 non-null  float64
 17  혈색소          44553 non-null  float64
 18  요단백          44553 non-null  float64
 19  혈청크레

In [125]:
df_test.head()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11139 entries, 0 to 11138
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   ID           11139 non-null  int64  
 1   성별코드         11139 non-null  object 
 2   연령대코드(5세단위)  11139 non-null  int64  
 3   신장(5Cm단위)    11139 non-null  int64  
 4   체중(5Kg단위)    11139 non-null  int64  
 5   허리둘레         11139 non-null  float64
 6   시력(좌)        11139 non-null  float64
 7   시력(우)        11139 non-null  float64
 8   청력(좌)        11139 non-null  float64
 9   청력(우)        11139 non-null  float64
 10  수축기혈압        11139 non-null  float64
 11  이완기혈압        11139 non-null  float64
 12  식전혈당(공복혈당)   11139 non-null  float64
 13  총콜레스테롤       11139 non-null  float64
 14  트리글리세라이드     11139 non-null  float64
 15  HDL콜레스테롤     11139 non-null  float64
 16  LDL콜레스테롤     11139 non-null  float64
 17  혈색소          11139 non-null  float64
 18  요단백          11139 non-null  float64
 19  혈청크레

In [127]:
df_y.head()
df_y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44553 entries, 0 to 44552
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      44553 non-null  int64
 1   흡연상태    44553 non-null  int64
dtypes: int64(2)
memory usage: 696.3 KB


In [189]:
# not null
# 성별 코드, 치석, 구강검진수검여부 -> encoding
df_sum = pd.concat([df_X, df_test])
df_sum.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55692 entries, 0 to 11138
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   ID           55692 non-null  int64  
 1   성별코드         55692 non-null  object 
 2   연령대코드(5세단위)  55692 non-null  int64  
 3   신장(5Cm단위)    55692 non-null  int64  
 4   체중(5Kg단위)    55692 non-null  int64  
 5   허리둘레         55692 non-null  float64
 6   시력(좌)        55692 non-null  float64
 7   시력(우)        55692 non-null  float64
 8   청력(좌)        55692 non-null  float64
 9   청력(우)        55692 non-null  float64
 10  수축기혈압        55692 non-null  float64
 11  이완기혈압        55692 non-null  float64
 12  식전혈당(공복혈당)   55692 non-null  float64
 13  총콜레스테롤       55692 non-null  float64
 14  트리글리세라이드     55692 non-null  float64
 15  HDL콜레스테롤     55692 non-null  float64
 16  LDL콜레스테롤     55692 non-null  float64
 17  혈색소          55692 non-null  float64
 18  요단백          55692 non-null  float64
 19  혈청크레아티닌  

In [190]:
df_sum.head()

ID 성별코드  연령대코드(5세단위)  신장(5Cm단위)  체중(5Kg단위)  허리둘레  시력(좌)  시력(우)  청력(좌)  \
0   0    F           40        155         60  81.3    1.2    1.0    1.0   
1   1    F           40        160         60  81.0    0.8    0.6    1.0   
2   2    M           55        170         60  80.0    0.8    0.8    1.0   
3   3    M           40        165         70  88.0    1.5    1.5    1.0   
4   4    F           40        155         60  86.0    1.0    1.0    1.0   

   청력(우)  ...  LDL콜레스테롤   혈색소  요단백  혈청크레아티닌  (혈청지오티)AST  (혈청지오티)ALT  감마지티피  \
0    1.0  ...     126.0  12.9  1.0      0.7        18.0        19.0   27.0   
1    1.0  ...     127.0  12.7  1.0      0.6        22.0        19.0   18.0   
2    1.0  ...     151.0  15.8  1.0      1.0        21.0        16.0   22.0   
3    1.0  ...     226.0  14.7  1.0      1.0        19.0        26.0   18.0   
4    1.0  ...     107.0  12.5  1.0      0.6        16.0        14.0   22.0   

   구강검진수검여부  치아우식증유무  치석  
0         Y      0.0   Y  
1         Y      0.0   Y  
2         Y      0.0   N  
3         Y      0.0   Y  
4         Y      0.0   N  

[5 rows x 26 columns]

In [191]:
df_sum = pd.get_dummies(
    df_sum,
    columns=['성별코드', '구강검진수검여부', '치석'],
    drop_first=False
)

In [192]:
df_sum.head()

ID  연령대코드(5세단위)  신장(5Cm단위)  체중(5Kg단위)  허리둘레  시력(좌)  시력(우)  청력(좌)  청력(우)  \
0   0           40        155         60  81.3    1.2    1.0    1.0    1.0   
1   1           40        160         60  81.0    0.8    0.6    1.0    1.0   
2   2           55        170         60  80.0    0.8    0.8    1.0    1.0   
3   3           40        165         70  88.0    1.5    1.5    1.0    1.0   
4   4           40        155         60  86.0    1.0    1.0    1.0    1.0   

   수축기혈압  ...  혈청크레아티닌  (혈청지오티)AST  (혈청지오티)ALT  감마지티피  치아우식증유무  성별코드_F  \
0  114.0  ...      0.7        18.0        19.0   27.0      0.0    True   
1  119.0  ...      0.6        22.0        19.0   18.0      0.0    True   
2  138.0  ...      1.0        21.0        16.0   22.0      0.0   False   
3  100.0  ...      1.0        19.0        26.0   18.0      0.0   False   
4  120.0  ...      0.6        16.0        14.0   22.0      0.0    True   

   성별코드_M  구강검진수검여부_Y   치석_N   치석_Y  
0   False        True  False   True  
1   False        True  False   True  
2    True        True   True  False  
3    True        True  False   True  
4   False        True   True  False  

[5 rows x 28 columns]

In [193]:
# 다시 data split
df_X = df_sum[:44553]
df_test = df_sum[44553:]
print(df_X.shape)
print(df_test.shape)

(44553, 28)
(11139, 28)


In [136]:
df_y

ID  흡연상태
0          0     0
1          1     0
2          2     1
3          3     0
4          4     0
...      ...   ...
44548  55686     0
44549  55687     0
44550  55688     0
44551  55689     1
44552  55690     0

[44553 rows x 2 columns]

In [195]:
X = df_X
y = df_y['흡연상태']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [196]:
# 모델링
rfc = RandomForestClassifier(random_state = 42, max_depth = 5)
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, random_state=42)

In [197]:
pred = rfc.predict(X_test)
print(pred)

[0 0 1 ... 0 1 1]


In [198]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_squared_error
print("Accuracy : ", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))
print(mean_squared_error(y_test, pred))

Accuracy :  0.7538996745595331
              precision    recall  f1-score   support

           0       0.85      0.74      0.79      5651
           1       0.63      0.78      0.70      3260

    accuracy                           0.75      8911
   macro avg       0.74      0.76      0.75      8911
weighted avg       0.77      0.75      0.76      8911

[[4182 1469]
 [ 724 2536]]
0.24610032544046684


In [199]:
pred_train = rfc.predict(X_train)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_squared_error

print("Accuracy : ", accuracy_score(y_train, pred_train))
print(classification_report(y_train, pred_train))
print(confusion_matrix(y_train, pred_train))
print("mse : ", mean_squared_error(y_train, pred_train))

Accuracy :  0.7484989618988833
              precision    recall  f1-score   support

           0       0.85      0.73      0.79     22550
           1       0.63      0.78      0.70     13092

    accuracy                           0.75     35642
   macro avg       0.74      0.76      0.74     35642
weighted avg       0.77      0.75      0.75     35642

[[16457  6093]
 [ 2871 10221]]
mse :  0.2515010381011167


In [180]:
# test
pred_test = rfc.predict(df_test)
print(pred_test)

[0 0 1 ... 0 0 1]


In [181]:
result = pd.DataFrame(pred_test, columns=['흡연여부'])
result.to_csv("result.csv", index=False)

In [182]:
res = pd.read_csv("result.csv")
res.head()

흡연여부
0     0
1     0
2     1
3     1
4     1

In [183]:
# validation 비교
df_val = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/smoke/y_test.csv")
print(df_val['흡연상태'].value_counts())
print(res['흡연여부'].value_counts())

흡연상태
0    7036
1    4103
Name: count, dtype: int64
흡연여부
0    6116
1    5023
Name: count, dtype: int64


In [184]:
val = df_val['흡연상태']
res = res['흡연여부']
print("Accuracy Score:", accuracy_score(val, res))
print("Confusion Matrix:\n", confusion_matrix(val, res))
print("Classification Report:\n", classification_report(val, res))

Accuracy Score: 0.7484513870185834
Confusion Matrix:
 [[5175 1861]
 [ 941 3162]]
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.74      0.79      7036
           1       0.63      0.77      0.69      4103

    accuracy                           0.75     11139
   macro avg       0.74      0.75      0.74     11139
weighted avg       0.77      0.75      0.75     11139

